/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ServiceManager;

import Model.Service;
import Model.ServiceCatalog;
import Model.VehicleServiceManager;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author csong
 */
public class ServicesJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VehicleServiceManager vsManager;
    /**
     * Creates new form ServicesJPanel
     */
    public ServicesJPanel(JPanel container, VehicleServiceManager dataManager) {
        initComponents();
        
        this.userProcessContainer = container;
        this.vsManager = dataManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCost = new javax.swing.JLabel();
        lblMechanicFName = new javax.swing.JLabel();
        lblMechanicLName = new javax.swing.JLabel();
        lblServiceDuration = new javax.swing.JLabel();
        btnCreateService = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        fieldServiceType = new javax.swing.JTextField();
        fieldCost = new javax.swing.JTextField();
        fieldMechanicFName = new javax.swing.JTextField();
        fieldMechanicLName = new javax.swing.JTextField();
        fieldServiceDuration = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblCost.setText("Cost:");

        lblMechanicFName.setText("Mechanic's First Name:");

        lblMechanicLName.setText("Mechanic's Last Name:");

        lblServiceDuration.setText("Service Duration (hours):");

        btnCreateService.setText("Create Service");
        btnCreateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateServiceActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Services");

        lblServiceType.setText("Service Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnBack)
                        .addGap(223, 223, 223)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCost)
                            .addComponent(lblServiceType)
                            .addComponent(lblMechanicFName)
                            .addComponent(lblMechanicLName)
                            .addComponent(lblServiceDuration))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldServiceType)
                                .addComponent(fieldCost)
                                .addComponent(fieldMechanicFName)
                                .addComponent(fieldMechanicLName)
                                .addComponent(fieldServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceType)
                    .addComponent(fieldServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCost)
                    .addComponent(fieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechanicFName)
                    .addComponent(fieldMechanicFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechanicLName)
                    .addComponent(fieldMechanicLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDuration)
                    .addComponent(fieldServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnCreateService)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateServiceActionPerformed
        String serviceType = fieldServiceType.getText();
        double cost;
        String mechanicFirstName = fieldMechanicFName.getText();
        String mechanicLastName = fieldMechanicLName.getText();
        int serviceDuration;
        
        if (serviceType.isBlank() || mechanicFirstName.isBlank() || mechanicLastName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill out all the fields", "Error", JOptionPane.ERROR_MESSAGE);
            //pause
            return;
        }
        
        try {
            cost = Double.parseDouble(fieldCost.getText());
            if (cost < 0) {
                JOptionPane.showMessageDialog(null, "Cost cannot be a negative number", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the cost input (number)", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            serviceDuration = Integer.parseInt(fieldServiceDuration.getText());
            if (serviceDuration <= 0) {
                JOptionPane.showMessageDialog(null, "Service duration must be a positive integer", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the service Duration input (integer)", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // add service
        ServiceCatalog serviceCatalog = vsManager.getServiceCatalog();
        Service s = serviceCatalog.addService();
        s.setServiceType(serviceType);
        s.setMechanicFirstName(mechanicFirstName);
        s.setMechanicLastName(mechanicLastName);
        s.setCost(cost);
        s.setServiceDuration(serviceDuration);
        
        // dialog for success
        JOptionPane.showMessageDialog(this, "Service successfully created.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        // reset text fields
        fieldServiceType.setText("");
        fieldCost.setText("");
        fieldMechanicFName.setText("");
        fieldMechanicLName.setText("");
        fieldServiceDuration.setText("");
    }//GEN-LAST:event_btnCreateServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateService;
    private javax.swing.JTextField fieldCost;
    private javax.swing.JTextField fieldMechanicFName;
    private javax.swing.JTextField fieldMechanicLName;
    private javax.swing.JTextField fieldServiceDuration;
    private javax.swing.JTextField fieldServiceType;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblMechanicFName;
    private javax.swing.JLabel lblMechanicLName;
    private javax.swing.JLabel lblServiceDuration;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
