/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ServiceManager;

import Model.Owner;
import Model.Service;
import Model.ServiceCatalog;
import Model.Vehicle;
import Model.VehicleServiceManager;
import java.awt.CardLayout;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author csong
 */
public class VehicleOwnerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VehicleServiceManager vsManager;
    /**
     * Creates new form VehicleOwnerJPanel
     */
    public VehicleOwnerJPanel(JPanel container, VehicleServiceManager dataManager) {
        initComponents();
        
        this.userProcessContainer = container;
        this.vsManager = dataManager;
        populateServiceOpted();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOwnerLName = new javax.swing.JLabel();
        lblServiceDate = new javax.swing.JLabel();
        btnRegisterService = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblOwnerFName = new javax.swing.JLabel();
        VehicleDetailsJPanel = new javax.swing.JPanel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblRegistrationNumber = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblVehicleDetails = new javax.swing.JLabel();
        fieldMake = new javax.swing.JTextField();
        fieldModel = new javax.swing.JTextField();
        fieldRegistrationNumber = new javax.swing.JTextField();
        comboServiceOpted = new javax.swing.JComboBox<>();
        lblServiceOpted = new javax.swing.JLabel();
        fieldYear = new javax.swing.JTextField();
        fieldOwnerFName = new javax.swing.JTextField();
        fieldOwnerLName = new javax.swing.JTextField();
        fieldServiceDate = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblOwnerLName.setText("Owner Last Name:");

        lblServiceDate.setText("Service Date:");

        btnRegisterService.setText("Register Service");
        btnRegisterService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterServiceActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Owner Details");

        lblOwnerFName.setText("Owner First Name:");

        VehicleDetailsJPanel.setBackground(new java.awt.Color(153, 204, 255));

        lblMake.setText("Make:");

        lblModel.setText("Model:");

        lblRegistrationNumber.setText("Registration Number:");

        lblYear.setText("Year:");

        lblVehicleDetails.setText("Vehicle Details");

        comboServiceOpted.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboServiceOpted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServiceOptedActionPerformed(evt);
            }
        });

        lblServiceOpted.setText("Service Opted:");

        javax.swing.GroupLayout VehicleDetailsJPanelLayout = new javax.swing.GroupLayout(VehicleDetailsJPanel);
        VehicleDetailsJPanel.setLayout(VehicleDetailsJPanelLayout);
        VehicleDetailsJPanelLayout.setHorizontalGroup(
            VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel)
                            .addComponent(lblRegistrationNumber)
                            .addComponent(lblYear)
                            .addComponent(lblMake)
                            .addComponent(lblServiceOpted))
                        .addGap(31, 31, 31)
                        .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldRegistrationNumber)
                            .addComponent(fieldModel)
                            .addComponent(fieldMake)
                            .addComponent(comboServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldYear, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblVehicleDetails)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        VehicleDetailsJPanelLayout.setVerticalGroup(
            VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblVehicleDetails)
                .addGap(18, 18, 18)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(fieldMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(fieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrationNumber)
                    .addComponent(fieldRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(fieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceOpted))
                .addGap(25, 25, 25))
        );

        fieldServiceDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY-MM-DD"))));
        fieldServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldServiceDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnBack)
                        .addGap(254, 254, 254)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerLName)
                            .addComponent(lblOwnerFName)
                            .addComponent(lblServiceDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldOwnerFName, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(fieldOwnerLName)
                            .addComponent(fieldServiceDate))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(btnRegisterService))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(VehicleDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerFName)
                    .addComponent(fieldOwnerFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerLName)
                    .addComponent(fieldOwnerLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDate)
                    .addComponent(fieldServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(VehicleDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnRegisterService)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateServiceOpted() {
        //clear previous generated combo box
        comboServiceOpted.removeAllItems();
        
        // get the list of services and iterate
        ServiceCatalog serviceList = vsManager.getServiceCatalog();
        for(Service s:serviceList.getServices()) {
            comboServiceOpted.addItem(s.getServiceType());
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboServiceOptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboServiceOptedActionPerformed

    }//GEN-LAST:event_comboServiceOptedActionPerformed

    private void fieldServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldServiceDateActionPerformed

    private void btnRegisterServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterServiceActionPerformed
        // Get data from Owner fields
        String ownerFirstName = fieldOwnerFName.getText();
        String ownerLastName = fieldOwnerLName.getText();
        String serviceDateStr = fieldServiceDate.getText();
        LocalDate serviceDate;
        
        // Get data from Vehicle fields
        int year;
        String make = fieldMake.getText();
        String model = fieldModel.getText();
        String registrationNumber = fieldRegistrationNumber.getText();
        String selectedServiceType = (String) comboServiceOpted.getSelectedItem();
        
        // Check fields
        if (ownerFirstName.isEmpty() || ownerLastName.isEmpty() || serviceDateStr.isEmpty() || make.isEmpty() || model.isEmpty() || registrationNumber.isEmpty() || selectedServiceType == null) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // validate year
        try {
            year = Integer.parseInt(fieldYear.getText());
            if (year < 1950 || year > LocalDate.now().getYear()) {
                JOptionPane.showMessageDialog(this, "Please enter a valid year, later than 1950.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Year must be an integer", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // validate service data
        try {
            serviceDate = LocalDate.parse(serviceDateStr);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid date YYYY-MM-DD.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Create the objects
        Service selectedService = vsManager.getServiceCatalog().findService(selectedServiceType);
        if (selectedService == null) {
            JOptionPane.showMessageDialog(this, "The Service type does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Owner newOwner = new Owner();
        newOwner.setOwnerFirstName(ownerFirstName);
        newOwner.setOwnerLastName(ownerLastName);
        newOwner.setServiceDate(serviceDate);
        
        Vehicle newVehicle = vsManager.getVehicleDirectory().addVehicle();
        newVehicle.setMake(make);
        newVehicle.setModel(model);
        newVehicle.setYear(year);
        newVehicle.setRegistrationNumber(registrationNumber);
        newVehicle.setOwner(newOwner);
        newVehicle.setServiceOpted(selectedService);
        
        //Clear fields
        fieldOwnerFName.setText("");
        fieldOwnerLName.setText("");
        fieldServiceDate.setText("");
        fieldYear.setText("");
        fieldMake.setText("");
        fieldModel.setText("");
        fieldRegistrationNumber.setText("");
        comboServiceOpted.setSelectedIndex(0);
    }//GEN-LAST:event_btnRegisterServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VehicleDetailsJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterService;
    private javax.swing.JComboBox<String> comboServiceOpted;
    private javax.swing.JTextField fieldMake;
    private javax.swing.JTextField fieldModel;
    private javax.swing.JTextField fieldOwnerFName;
    private javax.swing.JTextField fieldOwnerLName;
    private javax.swing.JTextField fieldRegistrationNumber;
    private javax.swing.JFormattedTextField fieldServiceDate;
    private javax.swing.JTextField fieldYear;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerFName;
    private javax.swing.JLabel lblOwnerLName;
    private javax.swing.JLabel lblRegistrationNumber;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JLabel lblServiceOpted;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleDetails;
    private javax.swing.JLabel lblYear;
    // End of variables declaration//GEN-END:variables

}
