/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ServiceManager;

import Model.Owner;
import Model.Service;
import Model.ServiceCatalog;
import Model.Vehicle;
import Model.VehicleServiceManager;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author csong
 */
public class ViewVehicleDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private VehicleServiceManager vsManager;
    private Vehicle vehicle;
    /**
     * Creates new form ViewVehicleDetails
     */
    public ViewVehicleDetailsJPanel(JPanel container, VehicleServiceManager dataManager, Vehicle selectedVehicle) {
        initComponents();
        
        this.userProcessContainer = container;
        this.vsManager = dataManager;
        this.vehicle = selectedVehicle;
        
        populateServiceOpted();
        refreshTextfields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblOwnerFName = new javax.swing.JLabel();
        VehicleDetailsJPanel = new javax.swing.JPanel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblRegistrationNumber = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblVehicleDetails = new javax.swing.JLabel();
        fieldMake = new javax.swing.JTextField();
        fieldModel = new javax.swing.JTextField();
        fieldRegistrationNumber = new javax.swing.JTextField();
        comboServiceOpted = new javax.swing.JComboBox<>();
        lblServiceOpted = new javax.swing.JLabel();
        fieldYear = new javax.swing.JTextField();
        fieldOwnerFName = new javax.swing.JTextField();
        fieldOwnerLName = new javax.swing.JTextField();
        fieldServiceDate = new javax.swing.JFormattedTextField();
        lblOwnerLName = new javax.swing.JLabel();
        lblServiceDate = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Owner Details");

        lblOwnerFName.setText("Owner First Name:");

        VehicleDetailsJPanel.setBackground(new java.awt.Color(153, 204, 255));

        lblMake.setText("Make:");

        lblModel.setText("Model:");

        lblRegistrationNumber.setText("Registration Number:");

        lblYear.setText("Year:");

        lblVehicleDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVehicleDetails.setText("Vehicle Details");

        comboServiceOpted.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboServiceOpted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServiceOptedActionPerformed(evt);
            }
        });

        lblServiceOpted.setText("Service Opted:");

        javax.swing.GroupLayout VehicleDetailsJPanelLayout = new javax.swing.GroupLayout(VehicleDetailsJPanel);
        VehicleDetailsJPanel.setLayout(VehicleDetailsJPanelLayout);
        VehicleDetailsJPanelLayout.setHorizontalGroup(
            VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel)
                            .addComponent(lblRegistrationNumber)
                            .addComponent(lblYear)
                            .addComponent(lblMake)
                            .addComponent(lblServiceOpted))
                        .addGap(31, 31, 31)
                        .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldRegistrationNumber)
                            .addComponent(fieldModel)
                            .addComponent(fieldMake)
                            .addComponent(comboServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldYear, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblVehicleDetails)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        VehicleDetailsJPanelLayout.setVerticalGroup(
            VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleDetailsJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblVehicleDetails)
                .addGap(18, 18, 18)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(fieldMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(fieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrationNumber)
                    .addComponent(fieldRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(fieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(VehicleDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceOpted))
                .addGap(25, 25, 25))
        );

        fieldServiceDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        fieldServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldServiceDateActionPerformed(evt);
            }
        });

        lblOwnerLName.setText("Owner Last Name:");

        lblServiceDate.setText("Service Date:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnBack)
                        .addGap(254, 254, 254)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerLName)
                            .addComponent(lblOwnerFName)
                            .addComponent(lblServiceDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldOwnerFName, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(fieldOwnerLName)
                            .addComponent(fieldServiceDate))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(VehicleDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnSave)
                        .addGap(167, 167, 167)
                        .addComponent(btnUpdate)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerFName)
                    .addComponent(fieldOwnerFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwnerLName)
                    .addComponent(fieldOwnerLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceDate)
                    .addComponent(fieldServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(VehicleDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateServiceOpted() {
        //clear previous generated combo box
        comboServiceOpted.removeAllItems();
        
        // get the list of services and iterate
        ServiceCatalog serviceList = vsManager.getServiceCatalog();
        for(Service s:serviceList.getServices()) {
            comboServiceOpted.addItem(s.getServiceType());
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Get data from Owner fields
        String ownerFirstName = fieldOwnerFName.getText();
        String ownerLastName = fieldOwnerLName.getText();
        String serviceDateStr = fieldServiceDate.getText();
        LocalDate serviceDate;

        // Get data from Vehicle fields
        int year;
        String make = fieldMake.getText();
        String model = fieldModel.getText();
        String registrationNumber = fieldRegistrationNumber.getText();
        String selectedServiceType = (String) comboServiceOpted.getSelectedItem();

        // Check fields
        if (ownerFirstName.isEmpty() || ownerLastName.isEmpty() || serviceDateStr.isEmpty() || make.isEmpty() || model.isEmpty() || registrationNumber.isEmpty() || selectedServiceType == null) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // validate year
        try {
            year = Integer.parseInt(fieldYear.getText());
            if (year < 1950 || year > LocalDate.now().getYear()) {
                JOptionPane.showMessageDialog(this, "Please enter a valid year, later than 1950.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Year must be an integer", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // validate service data
        try {
            serviceDate = LocalDate.parse(serviceDateStr);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid date YYYY-MM-DD.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Create the objects
        Service selectedService = vsManager.getServiceCatalog().findService(selectedServiceType);
        if (selectedService == null) {
            JOptionPane.showMessageDialog(this, "The Service type does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update the existing Owner
        vehicle.getOwner().setOwnerFirstName(ownerFirstName);
        vehicle.getOwner().setOwnerLastName(ownerLastName);
        vehicle.getOwner().setServiceDate(serviceDate);
        
        // Update existing vehicle
        vehicle.setMake(make);
        vehicle.setModel(model);
        vehicle.setYear(year);
        vehicle.setRegistrationNumber(registrationNumber);
        vehicle.setServiceOpted(selectedService);
        
        JOptionPane.showMessageDialog(null, "Vehicle successfully updated", "Information", JOptionPane.INFORMATION_MESSAGE);

        setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        
        // This will reach to the previous panel and trigger an update
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageVehiclesJPanel manageVehiclesJPanel = (ManageVehiclesJPanel) lastPanel;
        manageVehiclesJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void refreshTextfields() {        
        fieldOwnerFName.setText(vehicle.getOwner().getOwnerFirstName());
        fieldOwnerLName.setText(vehicle.getOwner().getOwnerLastName());
        fieldYear.setText(String.valueOf(vehicle.getYear()));
        fieldMake.setText(vehicle.getMake());
        fieldModel.setText(vehicle.getModel());
        fieldRegistrationNumber.setText(vehicle.getRegistrationNumber());
        comboServiceOpted.setSelectedItem(vehicle.getServiceOpted().getServiceType());
        
        // Handle Date format
        // Get the service date
        LocalDate serviceDate = vehicle.getOwner().getServiceDate();
        
        // Format the LocalDate to a String and set the text field
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedDate = serviceDate.format(formatter);
        fieldServiceDate.setText(formattedDate);
    }
    
    private void setViewMode() {
        fieldOwnerFName.setEnabled(false);
        fieldOwnerLName.setEnabled(false);
        fieldServiceDate.setEnabled(false);
        fieldYear.setEnabled(false);
        fieldMake.setEnabled(false);
        fieldModel.setEnabled(false);
        fieldRegistrationNumber.setEnabled(false);
        comboServiceOpted.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void setEditMode() {
        fieldOwnerFName.setEnabled(true);
        fieldOwnerLName.setEnabled(true);
        fieldServiceDate.setEnabled(true);
        fieldYear.setEnabled(true);
        fieldMake.setEnabled(true);
        fieldModel.setEnabled(true);
        fieldRegistrationNumber.setEnabled(true);
        comboServiceOpted.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
    
    private void comboServiceOptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboServiceOptedActionPerformed

    }//GEN-LAST:event_comboServiceOptedActionPerformed

    private void fieldServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldServiceDateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VehicleDetailsJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboServiceOpted;
    private javax.swing.JTextField fieldMake;
    private javax.swing.JTextField fieldModel;
    private javax.swing.JTextField fieldOwnerFName;
    private javax.swing.JTextField fieldOwnerLName;
    private javax.swing.JTextField fieldRegistrationNumber;
    private javax.swing.JFormattedTextField fieldServiceDate;
    private javax.swing.JTextField fieldYear;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerFName;
    private javax.swing.JLabel lblOwnerLName;
    private javax.swing.JLabel lblRegistrationNumber;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JLabel lblServiceOpted;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleDetails;
    private javax.swing.JLabel lblYear;
    // End of variables declaration//GEN-END:variables
}
